//
//  WeatherViewController.swift
//  Forecasts
//
//  Created Z on 11/5/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WeatherViewController: UIViewController, WeatherViewProtocol {
    @IBAction func listActionButton(_ sender: UIButton) {
        
        presenter?.showCityView()
    }
    
    @IBAction func linkActionButton(_ sender: UIButton) {
        
        presenter?.showLinkView()
    }
    var presenter: WeatherPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
