//
//  WeatherProtocols.swift
//  Forecasts
//
//  Created Z on 11/5/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol WeatherWireframeProtocol: class {
    func showCityView()
    func showLinkView()
}
//MARK: Presenter -
protocol WeatherPresenterProtocol: class {
    func showCityView()
    func showLinkView()
    func countCell(section: Int)->Int
}

//MARK: Interactor -
protocol WeatherInteractorProtocol: class {

  var presenter: WeatherPresenterProtocol?  { get set }
}

//MARK: View -
protocol WeatherViewProtocol: class {

  var presenter: WeatherPresenterProtocol?  { get set }
}
