//
//  WeatherRouter.swift
//  Forecasts
//
//  Created Z on 11/5/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WeatherRouter: WeatherWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = WeatherViewController(nibName: nil, bundle: nil)
        let interactor = WeatherInteractor()
        let router = WeatherRouter()
        let presenter = WeatherPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    func showCityView() {
        let view = CityRouter.createModule()
        self.viewController?.navigationController?.pushViewController(view, animated: true)
    }
    
    func showLinkView() {
        let view = WebViewRouter.createModule()
        self.viewController?.navigationController?.pushViewController(view, animated: true)
    }
}
