//
//  WebViewViewController.swift
//  Forecasts
//
//  Created Z on 11/5/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import WebKit

class WebViewViewController: UIViewController, WebViewViewProtocol {
    @IBOutlet weak var webView: UIWebView!
    var presenter: WebViewPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        webView.delegate = self
      
        if let url = URL(string: RequestsDataAPI.webURL) {
            webView?.loadRequest(URLRequest(url: url))
        }
    }
}

extension WebViewViewController: UIWebViewDelegate {
}
