//
//  WebViewViewController.swift
//  Forecasts
//
//  Created Z on 11/5/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WebViewViewController: UIViewController, WebViewViewProtocol {

	var presenter: WebViewPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
