//
//  WebViewProtocols.swift
//  Forecasts
//
//  Created Z on 11/5/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol WebViewWireframeProtocol: class {

}
//MARK: Presenter -
protocol WebViewPresenterProtocol: class {

}

//MARK: Interactor -
protocol WebViewInteractorProtocol: class {

  var presenter: WebViewPresenterProtocol?  { get set }
}

//MARK: View -
protocol WebViewViewProtocol: class {

  var presenter: WebViewPresenterProtocol?  { get set }
}
