//
//  CityRouter.swift
//  Forecasts
//
//  Created Z on 11/5/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CityRouter: CityWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = CityViewController(nibName: nil, bundle: nil)
        let interactor = CityInteractor()
        let router = CityRouter()
        let presenter = CityPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    func showSearchCityView() {
        let view = SearchCityRouter.createModule()
        self.viewController?.navigationController?.pushViewController(view, animated: true)
    }
}
