//
//  CityProtocols.swift
//  Forecasts
//
//  Created Z on 11/5/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol CityWireframeProtocol: class {
    func showSearchCityView()
    func closeView()
}
//MARK: Presenter -
protocol CityPresenterProtocol: class {
    func countCell()->Int
    func closeView()
    func showSearchCityView()
    func addCity(citySearch: CitySearchModel?)
    func getNameCity(index: Int)->String
    func getTemprCity(index: Int)->String
    func deleteCity(index: Int)
}

//MARK: Interactor -
protocol CityInteractorProtocol: class {

    var presenter: CityPresenterProtocol?  { get set }
    
    func addCity(citySearch: CitySearchModel?)
}

//MARK: View -
protocol CityViewProtocol: class {
    var presenter: CityPresenterProtocol?  { get set }
    func update()
}

protocol CityNameSend: class {
    func getCity(citySearch: CitySearchModel?)
}
