//
//  CityRouter.swift
//  Forecasts
//
//  Created Z on 11/5/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CityRouter: CityWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        let view = CityViewController(nibName: nil, bundle: nil)
        let interactor = CityInteractor()
        let router = CityRouter()
        let presenter = CityPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    func showSearchCityView() {
        if let viewSearch = SearchCityRouter.createModule() as? SearchCityViewController {
            if let viewController = self.viewController as? CityViewController {
                viewSearch.delegate = viewController
                self.viewController?.navigationController?.present(viewSearch, animated: true, completion: nil)
            }
        }
    }
    
    func closeView(city: CityModel?) {
        guard let cityNew = city else { return }
        if let viewController = self.viewController as? CityViewController {
            viewController.delegate?.getForecasts(city: cityNew)
        }
        self.viewController?.navigationController?.popViewController(animated: true)
    }
}
