//
//  SearchCityProtocols.swift
//  Forecasts
//
//  Created Z on 11/6/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SearchCityWireframeProtocol: class {
    func closeView()
}
//MARK: Presenter -
protocol SearchCityPresenterProtocol: class {
    func countCell()->Int
    func closeView()
}

//MARK: Interactor -
protocol SearchCityInteractorProtocol: class {

  var presenter: SearchCityPresenterProtocol?  { get set }
}

//MARK: View -
protocol SearchCityViewProtocol: class {

  var presenter: SearchCityPresenterProtocol?  { get set }
}
