//
//  SearchCityViewController.swift
//  Forecasts
//
//  Created Z on 11/6/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchCityViewController: UIViewController, SearchCityViewProtocol {

	var presenter: SearchCityPresenterProtocol?
    let cellIdentifier = "SearchCity"
    
    @IBOutlet weak var activityIndicator: UIActivityIndicatorView!
    weak var delegate: CityDelegate?
    
    @IBOutlet weak var searchBar: UISearchBar!
    @IBOutlet weak var cityTable: UITableView!
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
    }
    
	override func viewDidLoad() {
        super.viewDidLoad()
         self.activityIndicator.stopAnimating()
        searchBar.delegate = self
        searchBar.becomeFirstResponder()
        cityTable.delegate = self
        cityTable.dataSource = self
       
        cityTable.register(UINib(nibName: cellIdentifier, bundle: nil), forCellReuseIdentifier: cellIdentifier)
        cityTable.rowHeight = UITableView.automaticDimension
        cityTable.tableFooterView = UIView(frame: .zero)
    }
    
    func update() {
        DispatchQueue.main.async {
            self.cityTable.reloadData()
            self.activityIndicator.stopAnimating()
        }
    }
}

extension SearchCityViewController: UISearchBarDelegate {
    
    func searchBarCancelButtonClicked(_ searchBar: UISearchBar) {
        self.presenter?.closeView(citySearch: nil)
    }
    
    func searchBar(_ searchBar: UISearchBar, textDidChange searchText: String) {
       getSearch(textSearchBar: searchBar.text)
    }
    
    func searchBarSearchButtonClicked(_ searchBar: UISearchBar) {
        getSearch(textSearchBar: searchBar.text)
    }
    
    private func getSearch(textSearchBar: String?) {
         self.activityIndicator.startAnimating()
         self.presenter?.searchData(searchStr: textSearchBar)
    }
}

extension SearchCityViewController:  UITableViewDataSource, UITableViewDelegate {
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        let count = presenter?.countCell() ?? 0
        return count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: cellIdentifier, for: indexPath)
        if let cell = cell as? SearchCity {
            cell.nameCity.text = self.presenter?.getNameCity(index: indexPath.row)
        }
        return cell
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        guard let city = presenter?.getCity(index: indexPath.row) else { return }
        presenter?.closeView(citySearch: city)
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return UITableView.automaticDimension
    }
}
