//
//  SearchCityPresenter.swift
//  Forecasts
//
//  Created Z on 11/6/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchCityPresenter: SearchCityPresenterProtocol {

    weak private var view: SearchCityViewProtocol?
    var interactor: SearchCityInteractorProtocol?
    private let router: SearchCityWireframeProtocol

    init(interface: SearchCityViewProtocol, interactor: SearchCityInteractorProtocol?, router: SearchCityWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func countCell()->Int {
        var count: Int
        
        count = 12
        
        return count
    }

    func closeView() {
        router.closeView()
    }
}
