//
//  SearchCityViewController.swift
//  Forecasts
//
//  Created Z on 11/6/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchCityViewController: UIViewController, SearchCityViewProtocol {

	var presenter: SearchCityPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
