//
//  SearchCityInteractor.swift
//  Forecasts
//
//  Created Z on 11/6/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchCityInteractor: SearchCityInteractorProtocol {

    weak var presenter: SearchCityPresenterProtocol?
}
