//
//  WebViewPresenter.swift
//  Forecasts
//
//  Created Z on 11/5/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WebViewPresenter: WebViewPresenterProtocol {

    weak private var view: WebViewViewProtocol?
    var interactor: WebViewInteractorProtocol?
    private let router: WebViewWireframeProtocol

    init(interface: WebViewViewProtocol, interactor: WebViewInteractorProtocol?, router: WebViewWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
